### PR TITLE
Fix filename backup

### PR DESCRIPTION
**Pull request by Iwhite67**
for Get5 V0.11

### CODE REVIEW

**Comment by PhlexPlexico** [comment]
May I ask why you wish to place the server id? The file that gets created is only done so temporarily and then sent to the API which puts it in its respective folder for the current match. There shouldn't need to be a server ID included in this file. Plus if this changes, you would need to change the API as well

**Comment by PhlexPlexico** [comment]
Also isn't `Get5_GetServerID` a function call? Shouldn't it be `Get5_GetServerID()`?

**Comment by Iwhite67** [comment]
image

**Comment by PhlexPlexico** [comment]
Adjusted and updated the submodule dependency as well.

https://github.com/PhlexPlexico/G5WS/releases/tag/Nightly-84182c

Let me know if that works, thanks for contribution! :)

**Pull request closed without merging**
